#!/usr/bin/env python3
"""
Copia el esquema y los datos de MySQL a PostgreSQL.

Origen  : MySQL 8.0 en el servidor legacy, base `refautomex`. Sigue vivo y
          recibiendo escrituras a traves de la API de refautomex-calidad.com.
Destino : PostgreSQL 17 dentro del cluster EKS, base `refautomex`.

Se corre como un pod dentro del cluster: desde ahi hay salida a internet para
llegar al MySQL, y el Postgres se resuelve por DNS interno. Desde una Mac no
funciona - el sandbox rompe el handshake de ambos protocolos.

NO es incremental: recrea cada tabla desde cero. Correrlo dos veces deja el
mismo resultado, pero cualquier escritura hecha en Postgres entre una corrida
y otra se pierde. Es a proposito: mientras MySQL sea la fuente de verdad, el
destino es una copia y no un original.
"""

import os
import sys
from decimal import Decimal

import pymysql
import psycopg2
from psycopg2.extras import execute_values

# ---------------------------------------------------------------------------
# Mapeo de tipos
# ---------------------------------------------------------------------------

# La regla general es preservar el tipo mas cercano y no "mejorarlo": si en
# MySQL un precio es decimal(10,2), en Postgres tiene que seguir siendo
# numeric(10,2) y no float, o los totales dejan de cuadrar por redondeo.
TIPOS = {
    "int": "integer",
    "integer": "integer",
    "mediumint": "integer",
    "smallint": "smallint",
    "bigint": "bigint",
    "float": "real",
    "double": "double precision",
    "date": "date",
    "datetime": "timestamp",
    "timestamp": "timestamp",
    "time": "time",
    "year": "integer",
    "tinytext": "text",
    "text": "text",
    "mediumtext": "text",
    "longtext": "text",
    "json": "jsonb",
    "blob": "bytea",
    "mediumblob": "bytea",
    "longblob": "bytea",
    "tinyblob": "bytea",
}


def tipo_pg(col):
    """Traduce una columna de MySQL al tipo equivalente de Postgres."""
    t = col["DATA_TYPE"].lower()

    # tinyint(1) es como MySQL representa un booleano: no tiene tipo bool.
    # Cualquier otro tinyint es un entero chico de verdad.
    if t == "tinyint":
        return "boolean" if col["COLUMN_TYPE"].lower().startswith("tinyint(1)") else "smallint"

    if t in ("varchar", "char"):
        n = col["CHARACTER_MAXIMUM_LENGTH"]
        return f"{'varchar' if t == 'varchar' else 'char'}({n})" if n else "text"

    if t in ("decimal", "numeric"):
        p, s = col["NUMERIC_PRECISION"], col["NUMERIC_SCALE"]
        return f"numeric({p},{s})" if p is not None else "numeric"

    # enum y set se aplanan a text. Postgres tiene tipos enum propios, pero
    # crearlos ata el esquema a una lista de valores que la app todavia puede
    # estar cambiando; text acepta lo mismo sin bloquear nada.
    if t in ("enum", "set"):
        return "text"

    return TIPOS.get(t, "text")


# ---------------------------------------------------------------------------
# Lectura del esquema origen
# ---------------------------------------------------------------------------

def leer_esquema(cur, base):
    cur.execute(
        """
        SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, COLUMN_TYPE,
               CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE,
               IS_NULLABLE, EXTRA, COLUMN_DEFAULT, ORDINAL_POSITION
        FROM information_schema.COLUMNS
        WHERE TABLE_SCHEMA = %s
        ORDER BY TABLE_NAME, ORDINAL_POSITION
        """,
        (base,),
    )
    tablas = {}
    for c in cur.fetchall():
        tablas.setdefault(c["TABLE_NAME"], []).append(c)
    return tablas


def leer_claves(cur, base):
    cur.execute(
        """
        SELECT TABLE_NAME, COLUMN_NAME
        FROM information_schema.KEY_COLUMN_USAGE
        WHERE TABLE_SCHEMA = %s AND CONSTRAINT_NAME = 'PRIMARY'
        ORDER BY TABLE_NAME, ORDINAL_POSITION
        """,
        (base,),
    )
    pks = {}
    for r in cur.fetchall():
        pks.setdefault(r["TABLE_NAME"], []).append(r["COLUMN_NAME"])
    return pks


# ---------------------------------------------------------------------------
# Creacion en el destino
# ---------------------------------------------------------------------------

def ddl(tabla, columnas, pk):
    partes = []
    identidad = None

    for c in columnas:
        linea = f'  "{c["COLUMN_NAME"]}" {tipo_pg(c)}'

        # AUTO_INCREMENT no existe en Postgres. El equivalente moderno es una
        # columna IDENTITY. Va BY DEFAULT y no ALWAYS para que la carga pueda
        # insertar los IDs originales tal cual; con ALWAYS, Postgres los
        # rechazaria y renumeraria todo, rompiendo cada llave foranea.
        if "auto_increment" in (c["EXTRA"] or "").lower():
            linea += " GENERATED BY DEFAULT AS IDENTITY"
            identidad = c["COLUMN_NAME"]

        # Los DEFAULT hay que trasladarlos, no son cosmetica: `concepto.type`
        # y `concepto.pedido` son NOT NULL con default en MySQL, asi que la
        # app inserta sin mencionarlas. Sin el default, ese mismo INSERT falla
        # en Postgres con "null value violates not-null constraint".
        por_defecto = c.get("COLUMN_DEFAULT")
        if por_defecto is not None and "auto_increment" not in (c["EXTRA"] or "").lower():
            texto = str(por_defecto)
            if texto.upper() in ("CURRENT_TIMESTAMP", "NOW()"):
                linea += " DEFAULT CURRENT_TIMESTAMP"
            elif tipo_pg(c) in ("integer", "bigint", "smallint", "real", "double precision") \
                    or tipo_pg(c).startswith("numeric"):
                linea += f" DEFAULT {texto}"
            elif tipo_pg(c) == "boolean":
                linea += f" DEFAULT {'true' if texto not in ('0', 'false') else 'false'}"
            else:
                escapado = texto.replace("'", "''")
                linea += f" DEFAULT '{escapado}'"

        if c["IS_NULLABLE"] == "NO":
            linea += " NOT NULL"

        partes.append(linea)

    if pk:
        cols = ", ".join(f'"{c}"' for c in pk)
        partes.append(f"  PRIMARY KEY ({cols})")

    cuerpo = ",\n".join(partes)
    return f'CREATE TABLE "{tabla}" (\n{cuerpo}\n);', identidad


def limpiar(v):
    """Ajusta valores que los dos motores representan distinto."""
    # MySQL admite '0000-00-00' como fecha; Postgres no acepta esa fecha
    # porque no existe. Se guarda como NULL, que es lo que significaba.
    if isinstance(v, str) and v.startswith("0000-00-00"):
        return None
    # MySQL permite \x00 dentro de un varchar; Postgres lo rechaza siempre.
    if isinstance(v, str) and "\x00" in v:
        return v.replace("\x00", "")
    return v


def main():
    my = pymysql.connect(
        host=os.environ["MYSQL_HOST"],
        port=int(os.environ.get("MYSQL_PORT", 3306)),
        user=os.environ["MYSQL_USER"],
        password=os.environ["MYSQL_PASSWORD"],
        database=os.environ["MYSQL_DB"],
        cursorclass=pymysql.cursors.DictCursor,
        charset="utf8mb4",
    )
    pg = psycopg2.connect(os.environ["PG_DSN"])
    pg.autocommit = False

    base = os.environ["MYSQL_DB"]
    with my.cursor() as cur:
        esquema = leer_esquema(cur, base)
        claves = leer_claves(cur, base)

    print(f">> {len(esquema)} tablas en MySQL/{base}\n")
    resumen = []

    for tabla, columnas in sorted(esquema.items()):
        pk = claves.get(tabla, [])
        crear, identidad = ddl(tabla, columnas, pk)
        nombres = [c["COLUMN_NAME"] for c in columnas]

        with pg.cursor() as pcur:
            # CASCADE porque una tabla vieja puede tener vistas colgando.
            pcur.execute(f'DROP TABLE IF EXISTS "{tabla}" CASCADE;')
            pcur.execute(crear)

        with my.cursor() as mcur:
            mcur.execute(f"SELECT * FROM `{tabla}`")
            filas = mcur.fetchall()

        if filas:
            valores = [tuple(limpiar(f[n]) for n in nombres) for f in filas]
            cols = ", ".join(f'"{n}"' for n in nombres)
            with pg.cursor() as pcur:
                execute_values(
                    pcur,
                    f'INSERT INTO "{tabla}" ({cols}) VALUES %s',
                    valores,
                    page_size=1000,
                )

            # Insertar IDs explicitos no mueve el contador de la secuencia.
            # Sin este ajuste, el primer INSERT de la app intentaria reusar el
            # id 1 y chocaria contra la llave primaria.
            if identidad:
                with pg.cursor() as pcur:
                    pcur.execute(
                        f"""SELECT setval(
                              pg_get_serial_sequence('"{tabla}"', '{identidad}'),
                              COALESCE((SELECT MAX("{identidad}") FROM "{tabla}"), 1)
                            );"""
                    )

        pg.commit()
        resumen.append((tabla, len(filas)))
        print(f"  {tabla:<30} {len(filas):>7} filas")

    print(f"\n>> total: {sum(n for _, n in resumen):,} filas en {len(resumen)} tablas")
    my.close()
    pg.close()


if __name__ == "__main__":
    sys.exit(main())
